### ISSUE TITLE
User Account

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.cool.web#1]
Add user account features (login, google/facebook oauth, add/edit/delete posts etc)

**Comment by ppantilla** [comment]
Will start on this task on Monday thanks!On Jul 22, 2017 12:13 PM, Wintermute <notifications@github.com> wrote:Assigned #1 to @ppantilla.

**Comment by laisee** [comment]
Should just be about fixing the email function as that's reported as an
error on Heroku

**Comment by ppantilla** [comment]
can you send me a link/shot/text snippet for the error?

**Comment by ppantilla** [comment]
oh checking papertrail

**Comment by ppantilla** [comment]
got this one.  Heroku doesnt seem to link PHP Mail, so reconfigured to use gmail as an SMTP server.  seems to work fine now.  Just received an email from bbninja for a password reset.

**Comment by laisee** [comment]
signed up new account with my dbs account, did not receive an email. can you check?

**Comment by ppantilla** [comment]
Ok.  nothing in the spam or filter folders?

**Comment by ppantilla** [comment]
screenshot of backend approvals screen,

**Comment by laisee** [comment]
May have been filtered out upstream by DBS security. 

As long as you have any errors in getting the new user notification or forwarding on to me

**Comment by ppantilla** [comment]
there are a couple of things that I think are caused by heroku being read only.:
1. Registered Users cant log in because Heroku wont let Easysocial save server side login tokens. 2. Also cant upload user pics, as these are also saved on the file system.
Probably better if we do digital ocean for production and heroku for staging.

**Comment by laisee** [comment]
hmmm. local file access is technically possible. maybe just need the right permissions?

**Comment by ppantilla** [comment]
perhaps, you mean like this?How can I give permissions to specific folders on heroku?

  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
How can I give permissions to specific folders on heroku?
 I'm trying to install thelia on heroku, but I've problems with permissions on folders. How can I make ch...  |   |

  |

  |

**Comment by laisee** [comment]
did a little googling ... the Heroku instance("dyno") does have local file access to $HOME and /tmp. But all files are ephemeral and vanish along with instance on reconfig/restart ...

A better option could be to use the laravel driver for AWS S3, seems to be planty of code examples and StackOverflow explanations on how to make it work under Heroku.

Of course, if everything works fine under Digital Ocean then no point in doing extra work for bbninja.co

**Comment by ppantilla** [comment]
yeah probably time better spent just pushing out to Digital Ocean.  How do I do that?

**Comment by laisee** [comment]
hmmm. clicking on https://www.digitalocean.com/products/one-click-apps/joomla leads to 404 page :-0

**Comment by laisee** [comment]
Can you check if AWS offers a compatible solution covering easysocial?

https://aws.amazon.com/marketplace/pp/B00NNZUP54

**Comment by ppantilla** [comment]
This one should support easysocial already, as its a joomla component, and it is tightly coupled to joomla structures (user acl, component interfaces etc)

**Comment by ppantilla** [comment]
I'd probably go for a straight push as a typical LAMP app, no diff from WP, drupal, larvel etc.

**Comment by ppantilla** [comment]
Logo with outline

**Comment by laisee** [comment]
push this task to me for review once the user features are available on Atlantic.

**Comment by ppantilla** [comment]
setup on atlantic. up for review.

**Comment by laisee** [comment]
Account login via social media 
- Google OK
- Facebook OK
- Twitter FAIL:
An error has occured while processing the request
[Site:BBNinja] Could not connect to Twitter
Please verify the Twitter configuration in your OneAll account.
If you are the owner of this website then you need to follow the setup guide here: https://app.oneall.com/applications/application/providers/provider/?applicationid=389649&providerid=3
- Steam FAIL
Same text as Twitter with Steam link below
https://app.oneall.com/applications/application/providers/provider/?applicationid=389649&providerid=14

**Comment by ppantilla** [comment]
twitter configured and tested as working.  still need to buy a game in steam to be able to setup the id and secret

**Comment by laisee** [comment]
I have steam account

**Comment by ppantilla** [comment]
oh good.  could you do these steps for me?

1 Sign-in with your existing Steam account or create a new account.
You can only create a new API Key if you have at least one paid game in your account and you can only create one single API Key per account.
2 Open the page http://steamcommunity.com/dev/apikey in your browser.
3 Fill out the field with the value below and click on Register.
Domain Name:: bbninja.api.oneall.com
4 You instantly receive a new API Key

Just send me the key here and ill stick it in and were done for this one.

**Comment by ppantilla** [comment]
setup and tested.
