### ISSUE TITLE
Link Updates

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.cool.web#16]
wrote the first ticket for this on the wrong board.  this is the right one

email: esportsrcool@gmail.com
twitter: @esportscool
linkedin: https://www.linkedin.com/in/e-sports-9053bb147/
instagram: https://www.instagram.com/esports.cool

Can you change fb/twitter/etc links at op to be just icons like the footer section.
rearrange so that orders is from left ( icons - About Us - Games - Login/Register )
change copyright text to "Copyright (c) 2015 - 2017 E-sports.cool using js or php code from http://updateyourfooter.com

**Comment by laisee** [comment]
wrong board

**Comment by laisee** [comment]
Links are not resolving correctly e.g. http://45.58.45.127/www.facebook.com/esportscool for facebook. Same issue for twitter, instagram

**Comment by laisee** [comment]
twitter URL is now:  https://twitter.com/ESportsCool

**Comment by ppantilla** [comment]
yup sorry didnt update the http://.  Was working on the custom css.  to remove the all-caps.  Unless you are fine with it all caps?

**Comment by ppantilla** [comment]
otherwise pushing to review

**Comment by laisee** [comment]
Prefer same font as footer tbh

**Comment by ppantilla** [comment]
alright will need to override the less for that.

**Comment by ppantilla** [comment]
done.  you'll need to clear browser cache and hard reload to see changes

**Comment by laisee** [comment]
tried clearing cache and also used safari: the Copyright is not correct.
![Screen Shot 2017-08-12 at 7.20.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455f16b7191a37ff1102b4f5e5b5ecc3c4a4356bcbbd671f3e57862804e0ee4d66f0b74c36914ffe9844de901ba27de1980e3bdd81dd2f42f67b6d5db1063474f4dcbed5727a29f41c95df649e44e53ac143064e77e2431.png)

**Comment by ppantilla** [comment]
sorry this should be good now.
