### ISSUE TITLE
Link on login page generates error

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.cool.web#18]
Clicking on "register" link in sign-in page sends user to another page with odd message. See attached images

**Comment by laisee** [comment]
![screenshot 2017-08-10 13 31 45](https://user-images.githubusercontent.com/5905130/29155750-90c98188-7dd0-11e7-8655-05fa7aea8702.png)
![screenshot 2017-08-10 13 31 55](https://user-images.githubusercontent.com/5905130/29155749-90c8fc22-7dd0-11e7-9a87-4c0fa5421069.png)

**Comment by ppantilla** [comment]
might have been the redirection that I enabled the other day.  let me check.

**Comment by ppantilla** [comment]
yup changed this back to full reg.  also got rid of the Education and URL fields
