### ISSUE TITLE
change social media icons to common 'login' versions

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.cool.web#19]
Use icons like attached image

**Comment by laisee** [comment]
[Uploading Screenshot 2017-08-10 13.39.55.png...]

**Comment by ppantilla** [comment]
done.  limited to thes available large icons in freemium plan.   Styling change requires an upgrade to a basic paid plan.

**Comment by laisee** [comment]
Good enough for now. Checked and the login works.
