### ISSUE TITLE
Final issues for E-Sports web (alpha)

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.cool.web#21]
- change address in email signup for whitepaper (Gavin)
 - change description to "creating white paper now ..." (Gavin)
- re-order menu list (s/media icons, about us, games, sign-in/register, about tokens) (Gavin) 
 - move "Contact" to footer (Peter)
 - Don't show both "Login/Register" and "Login" together (Peter)
 - Don't show "Logout" and "Login" together (Login panel shows 'logout' button' (Peter)

**Comment by ppantilla** [comment]
would you prefer to keep the dropdown or the regular html layout login form as the  login ?  the menu css  is biased towards aligning the dropdown box with the left edge of the menu item, so the login gets pushed off screen towards the right ,

**Comment by laisee** [comment]
Regular one is OK for me.

**Comment by ppantilla** [comment]
ok will disable the dropdown

**Comment by ppantilla** [comment]
Other notes for the twitch icon.  Seems that icon-twitch is only available in font awesome 4.2 which is with the later version of Gantry, our template's underlying framework.  As we cant be assured that nothing will break in our rt-paradigm, i suggest we defer the icon update until we are ready to get the licensed copies of the template as well as easysocial.

**Comment by laisee** [comment]
still seeing two menu items once user is logged in. See attached image.
![Screen Shot 2017-08-20 at 1.21.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f36b7191a379f1102a4f5b5f5ecc3c4a4356bcbbd671f3e57862804e0ee4d66f0b74c36914ffe9844de901ba27de1980e3bdd81dd2f42f67b6d5db1063474f4dcbed5727a39841c95df648e34d5da1163660e1732431.png)

**Comment by ppantilla** [comment]
someone gave your userid the guest permission when assigning you to user groups.  Just having administrator should do.  trimmed it down you should be fine.

**Comment by laisee** [comment]
Created backlog item for fixing later.

Whats cost to upgrade easysocial, by the way?
