### ISSUE TITLE
CM Feedback on Excel - Budget

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.cool.web#25]
"Excel Sheet: A one-year forecast is not enough - sorry, but most will ask for five and settle for three years. You need to get some CAGR figures for the e-sports industry as a whole, and in Asia. You need to be able to substantiate the figures. And you need to plug in your income projections."

**Comment by chrismaden** [comment]
I've attached an idea of the minimum possible. You will need to update the expenses with reasonable projections for the first four years.

The hard part of it is the revenue model, and what the model so far shows is that you've paid no attention to how YOU will monetise this site. I assume that your bread and butter is tokens, so you need to estimate how many tokens / user, transactions / user and fee / transaction. You need to factor in the number of e-sports on your site.

I would also say that a linear relationship between users and income is less interesting while a somewhat exponential relationship is more interesting. But you need to be able to justify whatever relationship you come up with. And you need to put limits on it - no matter how many e-sports and users there are, there are only so many transactions that will happen.

 
[e-sportsdotcool-budget-2017-08-17.xlsx](https://github.com/e-sportsdotcool/esports.cool.web/files/1230240/e-sportsdotcool-budget-2017-08-17.xlsx)

**Comment by laisee** [comment]
Thanks, will take a look at this tonight.

I am deliberately not putting focus on tokens or token revenue at this time
because a) it obscures the simple plan to focus on building user count b) I
don't want this to be a 'crypto' startup until I'm sure tokens add value
for the fans c) there is high chance of regulatory smackdown on tokens soon

Get rooted yet?

Cheers
Gavin

Gavin
