### ISSUE TITLE
Embed html Wallet from NanoWallet

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.cool.web#28]
add wallet as Joomla plugin within iframe or similar

**Comment by laisee** [comment]
can remove the text panel on right hand side.
![Screen Shot 2017-08-17 at 10.12.59 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455f46b7191a379ef0c2a53415a47bc30254d58eeb9cb74fce36f34985619e8d86a5d20c63845a9ebd319ed57ba208c1ad3b3e98b1e91fa2137a5dad11b61435c52dcbd4f3fb2984fc05ffc4ae44d57ad103066ee753174448653.png)

**Comment by laisee** [comment]
remove all the content(tabs, functions) that is not directly related to basic wallet functions i.e. list accounts, show balance per account, list transactions for selected account, send/receive tokens, provide link at top to "Services")

Regarding wallet UI design, lets chat later in the day on how minimal view of functions could look.

**Comment by ppantilla** [comment]
ok much better.  i.ve disabled the demo test panel.   haven't flushed it to 100% width as thats governed by boostrap grid.

**Comment by ppantilla** [comment]
styling continuing to be consistent overall

**Comment by ppantilla** [comment]
for review (except  for hover color  on menu)

**Comment by laisee** [comment]
Will take a look today

**Comment by laisee** [comment]
here is a sketch for next stage of wallet: https://www.gliffy.com/go/html5/12182425

Dev Milestones:
1. add balance to easy social home page (link to user account by wallet address)
2. add link to open wallet in new panel within easy social(?). Should look to be integrated and same styling
3. wallet will show balance + last ten transactions on first tab,  more complete txn list on second tab, send/receive function on 3rd tab. 

Take a look at the sketch and we can discuss when you are ready

**Comment by ppantilla** [comment]
tried moving the code in to the joomla codebase in different ways, seems the wallet doesn't display all its working parts, leads me to think its a monolithic view.

**Comment by ppantilla** [comment]
have code displaying a wallet balance, need to link it to an easysocial user now.  Still in surgery.

**Comment by laisee** [comment]
Cool, shall I take a look?

**Comment by ppantilla** [comment]
done with balance + rudimentary happy flow error checking .

**Comment by laisee** [comment]
Looks good and works for the basic testing I did .e. switching public key from one wallet to another updated balance correctly. See my other comments for questions and updates

**Comment by laisee** [comment]
Q: Should we keep public key AND address? One reason I can think of is to allow sending tokens to the players wallet.

**Comment by laisee** [comment]
N.b. the amount displayed is the NEM wallet balance, not the balance of the COOL tokens. NEM would also work fine but its too expensive for e.g. tipping or micropayments so we will need to change the balance check to use xemex.cool as the relevant currency

**Comment by laisee** [comment]
N.B. User may have more than one account within the wallet, so balances may be spread across accounts. We will not enable the multi-account feature for now but the API call may return multiple items still.

**Comment by ppantilla** [comment]
got this,  will support the case.  Will need to know how to interface with COOL tokens when it is available.

**Comment by ppantilla** [comment]
I think I included the wallet address so that it can be queried to be able to receive tokens.  I am thinking of putting the send button on the profile page as well. i.e. Send money to this guy/gal

**Comment by laisee** [comment]
I can send some cool tokens to a wallet if you give me an address

Gavin

**Comment by laisee** [comment]
Check comments in the git embed wallet task, I added sample API call for
getting list of tokens attached to an address. You will need to filter for
the cool token. It has namespace "esports" and mosaic name "cool"

Gavin

**Comment by ppantilla** [comment]
yup parsing

**Comment by ppantilla** [comment]
i feel it might make more sense though to report each account and its respective balance.

**Comment by laisee** [comment]
Can do that, but if you want to show on top left we may run out of space?
Or you need to have an expanding panel like the bitfinex one showing user
balances

first pic shows closed state, second show the "balances" title clicked and
balance data expanded.

Can we add backlog item to handle multiple accounts once the display of
transactions & send/receive is working? I feel we should keep to simplest
MVP version until we get enough actual user feedback

Gavin

**Comment by ppantilla** [comment]
ok added. so for now go for min viable one first that adds all COOL tokens?

**Comment by ppantilla** [comment]
yeah please do add cool tokens to a wallet i can query / test.

**Comment by laisee** [comment]
Yep. I imagine we could expand to have game-specific tokens later, but good
to stay with 1 for now.

**Comment by ppantilla** [comment]
new test account address: NDWQC5-A42S34-EVQQMY-RZDHB3-SV3BHY-EGBWP6-H6JD

**Comment by ppantilla** [comment]
happy flow multiple accounts , multiple mosaics code in place

**Comment by laisee** [comment]
"cool" - will check it out

**Comment by laisee** [comment]
tried to view accounts/mosaics but it doesn't seem to be using the keys

![Screen Shot 2017-08-26 at 12.50.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f56b7191a379ed0c2e51415f4ebc21254d58eeb9cb74fce36f34985619e8d86a5d20c63845a9ebd319ed57ba208c1ad3b3e98b1e91fa2137a5dad11b61435c52dcbd4f3fb29d49c15bfc4ae44d56a3113262e276357a458653.png)
![Screen Shot 2017-08-26 at 12.53.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f56b7191a379ed0c2e52415a4abc21254d58eeb9cb74fce36f34985619e8d86a5d20c63845a9ebd319ed57ba208c1ad3b3e98b1e91fa2137a5dad11b61435c52dcbd4f3fb29d48c95afc4ae44d56a3113262e276327c448653.png)

**Comment by ppantilla** [comment]
Might have created an error bec the second address field has the word "Address: " in front

**Comment by laisee** [comment]
I saw that in saved record. Entered the data again and saved for second
time, didn't see the additional text.
