### ISSUE TITLE
error on site when clicking user status

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.cool.web#47]
http://e-sports.cool/community/badges/item/20-newbie produces error "
Fatal error: Class 'NEM' not found in /var/www/html/plugins/system/sourcerer/helper.php(564) : runtime-created function on line 11"

**Comment by ppantilla** [comment]
brings up conflicting underlying NEM classdefs based on the context.  all fixed.

**Comment by laisee** [comment]
tested, fixed
