### ISSUE TITLE
Document OctoberCMS Content DB schema.

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.cool.web#7]
document schema for incoming/scraped content

**Comment by ppantilla** [comment]
may need to be moved to xemex

**Comment by ppantilla** [comment]
seems almost all of the content is stored as twig markup files.  How are we intending to put in content?

**Comment by laisee** [comment]
How is content normally added to this CMS?

**Comment by ppantilla** [comment]
The templates are twig markup HTML pages  and are organized into either partials, which basically are reusable snippets, and content, which is static content, i.e. not meant to house code/inline css/php.

There is a set of plugins that i installed with this from rainlab that store traditional content   types like blog posts & categories, forums:

**Comment by ppantilla** [comment]
-- Table structure for table `rainlab_forum_posts`
--

CREATE TABLE IF NOT EXISTS `rainlab_forum_posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `subject` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `content` text COLLATE utf8_unicode_ci,
  `content_html` text COLLATE utf8_unicode_ci,
  `topic_id` int(10) unsigned DEFAULT NULL,
  `member_id` int(10) unsigned DEFAULT NULL,
  `edit_user_id` int(11) DEFAULT NULL,
  `delete_user_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `rainlab_forum_posts_topic_id_index` (`topic_id`),
  KEY `rainlab_forum_posts_member_id_index` (`member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

**Comment by ppantilla** [comment]
-- Table structure for table `rainlab_blog_posts`
--

CREATE TABLE IF NOT EXISTS `rainlab_blog_posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned DEFAULT NULL,
  `title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `slug` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `excerpt` text COLLATE utf8_unicode_ci,
  `content` longtext COLLATE utf8_unicode_ci,
  `content_html` longtext COLLATE utf8_unicode_ci,
  `published_at` timestamp NULL DEFAULT NULL,
  `published` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `rainlab_blog_posts_user_id_index` (`user_id`),
  KEY `rainlab_blog_posts_slug_index` (`slug`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=3 ;

**Comment by ppantilla** [comment]
content items get entered either with a frontend plugin or by default in the backend cms.

**Comment by ppantilla** [comment]
the same backend cms also lets you edit the /page/partial/content items via a similar interface.

**Comment by ppantilla** [comment]
blog posts are organized by categories, so thats the only foreign key

**Comment by laisee** [comment]
Will use these schemas to write some content into tables, exposing the data via REST service.
